import { Product, Category, Review, Order } from './types';

export const PROVINCES = {
  en: [
    'Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampot', 
    'Kep', 'Kandal', 'Kampong Cham', 'Kampong Thom', 'Koh Kong', 
    'Prey Veng', 'Svay Rieng', 'Takeo', 'Pursat', 'Mondulkiri', 'Ratanakiri'
  ],
  km: [
    'ភ្នំពេញ', 'សៀមរាប', 'បាត់ដំបង', 'ព្រះសីហនុ', 'កំពត', 
    'កែប', 'កណ្តាល', 'កំពង់ចាម', 'កំពង់ធំ', 'កោះកុង', 
    'ព្រៃវែង', 'ស្វាយរៀង', 'តាកែវ', 'ពោធិ៍សាត់', 'មណ្ឌលគិរី', 'រតនគិរី'
  ]
};

// Keep for backward compatibility if needed, but we will use PROVINCES in App.tsx
export const CAMBODIA_PROVINCES = PROVINCES.en;

export const TRANSLATIONS = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.story': 'Our Story',
    'nav.dashboard': 'Dashboard',
    'hero.shop': 'Shop Collection',
    'hero.sub': 'Italian Science, Khmer Soul',
    'cat.shop': 'Shop By Category',
    'sect.newArrivals': 'New Arrivals',
    'sect.ourCollection': 'Our Collection',
    'btn.all': 'All',
    'btn.addToCart': 'Add to Cart',
    'btn.add': 'Add',
    'btn.checkout': 'Checkout Now',
    'btn.login': 'Login',
    'cart.title': 'Shopping Bag',
    'cart.empty': 'Your bag is empty.',
    'cart.subtotal': 'Subtotal',
    'wishlist.title': 'My Wishlist',
    'wishlist.empty': 'Your wishlist is empty.',
    'checkout.title': 'Checkout',
    'checkout.step1': 'Review Order',
    'checkout.step2': 'Shipping Info',
    'checkout.step3': 'Payment',
    'checkout.total': 'Total',
    'checkout.next': 'Next Step',
    'checkout.confirm': 'Confirm Payment',
    'checkout.back': 'Back',
    'checkout.scan': 'Scan to pay',
    'checkout.select_province': 'Select Province',
    'form.name': 'Full Name',
    'form.phone': 'Phone Number',
    'form.province': 'Province / City',
    'form.address': 'Address Details',
    'ai.title': 'CYRA Assistant',
    'ai.chat': 'Chat Support',
    'ai.doctor': 'Skin Doctor (AI)',
    'ai.upload': 'Upload Photo',
    'ai.camera': 'Take Photo',
    'ai.placeholder': 'Ask about products...',
    'ai.placeholder_skin': 'Add details about your skin...',
    'story.vision': 'The Vision',
    'story.vision_desc': 'Founders Marco & Sophea meet in Milan, uniting a passion for skincare.',
    'story.research': 'Botanical Research',
    'story.research_desc': 'Expeditions to Ratanakiri to discover rare Khmer healing herbs.',
    'story.formula': 'The Formula',
    'story.formula_desc': 'Italian labs perfect the micro-encapsulation of Lotus extract.',
    'story.launch': 'CYRA Launch',
    'story.launch_desc': 'The first flagship store opens in the heart of Phnom Penh.',
    'profile.title': 'My Profile',
    'profile.orders': 'Order History',
    'profile.member': 'Member Since',
    'status.Pending': 'Pending',
    'status.Processing': 'Processing',
    'status.Shipped': 'Shipped',
    'order.id': 'Order ID',
    'order.date': 'Date',
    'order.total': 'Total',
    'order.items': 'Items',
    'common.new': 'NEW',
    'common.reviews': 'Reviews',
    'common.verified': 'Verified',
    'story.est': 'Est. 2023',
    'story.legacy_prefix': 'The CYRA',
    'story.legacy_suffix': 'Legacy',
    'story.quote_start': 'We believe true radiance comes from the harmony of',
    'story.quote_highlight1': 'Italian scientific precision',
    'story.quote_mid': 'and',
    'story.quote_highlight2': 'Khmer natural purity',
    'story.italy_title': 'Italian Innovation',
    'story.italy_sub': 'Advanced Molecular Science',
    'story.italy_desc': 'Our journey begins in the heart of Milan, where world-class dermatologists engineer our formulas. Using advanced micro-encapsulation technology, we ensure that every drop of CYRA penetrates deep into the dermis, delivering hydration and repair where it matters most.',
    'story.khmer_title': 'Khmer Soul',
    'story.khmer_sub': "Nature's Ancient Wisdom",
    'story.khmer_desc': 'Grounded in the rich biodiversity of Cambodia, we ethically source our botanical ingredients. From the resilient Lotus flower of Battambang to the healing Turmeric of Ratanakiri, we honor the ancient beauty rituals passed down through generations.',
    'story.history': 'History',
    'story.journey': 'Our Journey',
  },
  km: {
    'nav.home': 'ទំព័រដើម',
    'nav.products': 'ផលិតផល',
    'nav.story': 'អំពីយើង',
    'nav.dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'hero.shop': 'ទិញទំនិញ',
    'hero.sub': 'បច្ចេកវិទ្យាអ៊ីតាលី ព្រលឹងខ្មែរ',
    'cat.shop': 'ទិញតាមប្រភេទ',
    'sect.newArrivals': 'ផលិតផលថ្មីៗ',
    'sect.ourCollection': 'បណ្ដុំផលិតផលរបស់យើង',
    'btn.all': 'ទាំងអស់',
    'btn.addToCart': 'ដាក់ចូលកន្ត្រក',
    'btn.add': 'បន្ថែម',
    'btn.checkout': 'គិតលុយ',
    'btn.login': 'ចូលគណនី',
    'cart.title': 'កន្ត្រកទំនិញ',
    'cart.empty': 'កន្ត្រករបស់អ្នកទទេ',
    'cart.subtotal': 'សរុប',
    'wishlist.title': 'បញ្ជីដែលចូលចិត្ត',
    'wishlist.empty': 'បញ្ជីរបស់អ្នកទទេ',
    'checkout.title': 'ការទូទាត់',
    'checkout.step1': 'ពិនិត្យការកម្មង់',
    'checkout.step2': 'ព័ត៌មានដឹកជញ្ជូន',
    'checkout.step3': 'ការទូទាត់',
    'checkout.total': 'សរុប',
    'checkout.next': 'បន្តទៀត',
    'checkout.confirm': 'បញ្ជាក់ការទូទាត់',
    'checkout.back': 'ត្រឡប់ក្រោយ',
    'checkout.scan': 'ស្កេនដើម្បីទូទាត់',
    'checkout.select_province': 'ជ្រើសរើសខេត្ត/ក្រុង',
    'form.name': 'ឈ្មោះពេញ',
    'form.phone': 'លេខទូរស័ព្ទ',
    'form.province': 'ខេត្ត / ក្រុង',
    'form.address': 'អាសយដ្ឋានលម្អិត',
    'ai.title': 'ជំនួយការ CYRA',
    'ai.chat': 'ជជែកសួរ',
    'ai.doctor': 'គ្រូពេទ្យស្បែក (AI)',
    'ai.upload': 'បង្ហោះរូបថត',
    'ai.camera': 'ថតរូប',
    'ai.placeholder': 'សួរអំពីផលិតផល...',
    'ai.placeholder_skin': 'បន្ថែមព័ត៌មានអំពីស្បែករបស់អ្នក...',
    'story.vision': 'ចក្ខុវិស័យ',
    'story.vision_desc': 'ស្ថាបនិក Marco & Sophea ជួបគ្នានៅ Milan ដើម្បីបង្កើតផលិតផលថែរក្សាស្បែក។',
    'story.research': 'ការស្រាវជ្រាវរុក្ខជាតិ',
    'story.research_desc': 'ការចុះទៅខេត្តរតនគិរីដើម្បីស្វែងរករុក្ខជាតិឱសថខ្មែរដ៏កម្រ។',
    'story.formula': 'រូបមន្ត',
    'story.formula_desc': 'មន្ទីរពិសោធន៍អ៊ីតាលីសម្រិតសម្រាំងការចម្រាញ់ផ្កាឈូក។',
    'story.launch': 'ការសម្ពោធ CYRA',
    'story.launch_desc': 'ហាងដំបូងបានបើកនៅកណ្តាលរាជធានីភ្នំពេញ។',
    'profile.title': 'ប្រវត្តិរូបរបស់ខ្ញុំ',
    'profile.orders': 'ប្រវត្តិការកម្មង់',
    'profile.member': 'សមាជិកតាំងពី',
    'status.Pending': 'រង់ចាំ',
    'status.Processing': 'កំពុងដំណើរការ',
    'status.Shipped': 'បានដឹកជញ្ជូន',
    'order.id': 'លេខកូដកម្មង់',
    'order.date': 'កាលបរិច្ឆេទ',
    'order.total': 'សរុប',
    'order.items': 'ទំនិញ',
    'common.new': 'ថ្មី',
    'common.reviews': 'រីវ្យូ',
    'common.verified': 'បានផ្ទៀងផ្ទាត់',
    'story.est': 'បង្កើតឡើងឆ្នាំ ២០២៣',
    'story.legacy_prefix': 'កេរ្តិ៍ដំណែល',
    'story.legacy_suffix': 'CYRA',
    'story.quote_start': 'យើងជឿជាក់ថាភាពស្រស់ស្អាតពិតកើតចេញពីភាពសុខដុមនៃ',
    'story.quote_highlight1': 'បច្ចេកវិទ្យាវិទ្យាសាស្ត្រអ៊ីតាលី',
    'story.quote_mid': 'និង',
    'story.quote_highlight2': 'ភាពបរិសុទ្ធនៃធម្មជាតិខ្មែរ',
    'story.italy_title': 'នវានុវត្តន៍អ៊ីតាលី',
    'story.italy_sub': 'វិទ្យាសាស្ត្រម៉ូលេគុលកម្រិតខ្ពស់',
    'story.italy_desc': 'ដំណើររបស់យើងចាប់ផ្តើមនៅកណ្តាលទីក្រុង Milan ដែលជាកន្លែងអ្នកជំនាញសើស្បែកលំដាប់ពិភពលោកបង្កើតរូបមន្តរបស់យើង។ ដោយប្រើបច្ចេកវិជ្ជា micro-encapsulation កម្រិតខ្ពស់ យើងធានាថារាល់ដំណក់នៃ CYRA ជ្រាបចូលជ្រៅទៅក្នុងស្បែក ដោយផ្តល់នូវសំណើម និងការជួសជុលនៅកន្លែងដែលត្រូវការបំផុត។',
    'story.khmer_title': 'ព្រលឹងខ្មែរ',
    'story.khmer_sub': 'ប្រាជ្ញាបុរាណនៃធម្មជាតិ',
    'story.khmer_desc': 'ដោយផ្អែកលើជីវចម្រុះដ៏សម្បូរបែបនៃប្រទេសកម្ពុជា យើងស្វែងរករុក្ខជាតិឱសថដោយក្រមសីលធម៌។ ពីផ្កាឈូកនៃខេត្តបាត់ដំបង រហូតដល់រមៀតនៃខេត្តរតនគិរី យើងគោរពពិធីថែរក្សាសម្រស់បុរាណដែលបានបន្តរាប់ជំនាន់។',
    'story.history': 'ប្រវត្តិ',
    'story.journey': 'ដំណើររបស់យើង',
  }
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'face', name: 'Face Care', nameKm: 'ថែរក្សាមុខ', image: 'https://picsum.photos/id/64/200/200' },
  { id: 'body', name: 'Body Care', nameKm: 'ថែរក្សារាងកាយ', image: 'https://picsum.photos/id/65/200/200' },
  { id: 'sets', name: 'Value Sets', nameKm: 'ឈុតសន្សំសំចៃ', image: 'https://picsum.photos/id/66/200/200' },
  { id: 'serums', name: 'Serums', nameKm: 'សេរ៉ូម', image: 'https://picsum.photos/id/67/200/200' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'CYRA Night Repair Cream',
    nameKm: 'ក្រែមលាបមុខពេលយប់ CYRA',
    description: 'Advanced Italian formula designed to rejuvenate Khmer skin overnight. Reduces dark spots and hydrates deeply.',
    descriptionKm: 'រូបមន្តអ៊ីតាលីកម្រិតខ្ពស់ដែលត្រូវបានរចនាឡើងដើម្បីជួសជុលស្បែកខ្មែរពេញមួយយប់។ កាត់បន្ថយស្នាមអុចខ្មៅ និងផ្ដល់សំណើមជ្រៅ។',
    price: 25.00,
    costPrice: 12.00,
    category: 'Face Care',
    categoryKm: 'ថែរក្សាមុខ',
    image: 'https://picsum.photos/id/100/600/600',
    rating: 4.8,
    reviews: 124,
    isNewArrival: true,
  },
  {
    id: '2',
    name: 'Acne Clear Set',
    nameKm: 'ឈុតព្យាបាលមុន',
    description: 'Complete solution for acne-prone skin. Includes cleanser, toner, and spot treatment.',
    descriptionKm: 'ដំណោះស្រាយពេញលេញសម្រាប់ស្បែកងាយកើតមុន។ រួមបញ្ចូលទាំងហ្វូមលាងមុខ ទឹកជូតមុខ និងក្រែមលាបមុន។',
    price: 45.00,
    costPrice: 20.00,
    category: 'Value Sets',
    categoryKm: 'ឈុតសន្សំសំចៃ',
    image: 'https://picsum.photos/id/101/600/600',
    rating: 4.9,
    reviews: 89,
    isNewArrival: true,
  },
  {
    id: '3',
    name: 'Gold Radiance Serum',
    nameKm: 'សេរ៉ូមមាស ២៤K',
    description: 'Infused with 24k gold particles for an instant glow. Perfect for special occasions.',
    descriptionKm: 'ផ្សំឡើងពីភាគល្អិតមាស ២៤k សម្រាប់ភាពភ្លឺរលោងភ្លាមៗ។ សាកសមបំផុតសម្រាប់កម្មវិធីពិសេស។',
    price: 35.00,
    costPrice: 15.00,
    category: 'Serums',
    categoryKm: 'សេរ៉ូម',
    image: 'https://picsum.photos/id/102/600/600',
    rating: 4.7,
    reviews: 56,
  },
  {
    id: '4',
    name: 'Whitening Body Lotion',
    nameKm: 'ឡេលាបខ្លួនសាច់ស',
    description: 'Safe and effective whitening lotion with SPF 50. Protects and brightens.',
    descriptionKm: 'ឡេធ្វើឱ្យស្បែកស មានសុវត្ថិភាពនិងប្រសិទ្ធភាព ជាមួយ SPF 50។ ការពារ និងធ្វើឱ្យស្បែកភ្លឺថ្លា។',
    price: 18.00,
    costPrice: 8.00,
    category: 'Body Care',
    categoryKm: 'ថែរក្សារាងកាយ',
    image: 'https://picsum.photos/id/103/600/600',
    rating: 4.6,
    reviews: 210,
  },
  {
    id: '5',
    name: 'Gentle Foam Cleanser',
    nameKm: 'ហ្វូមលាងមុខ',
    description: 'pH-balanced cleanser that removes impurities without stripping natural oils.',
    descriptionKm: 'ហ្វូមលាងមុខដែលមានតុល្យភាព pH កម្ចាត់ភាពកខ្វក់ដោយមិនធ្វើឱ្យបាត់បង់ជាតិប្រេងធម្មជាតិ។',
    price: 12.00,
    costPrice: 4.00,
    category: 'Face Care',
    categoryKm: 'ថែរក្សាមុខ',
    image: 'https://picsum.photos/id/104/600/600',
    rating: 4.5,
    reviews: 150,
  }
];

export const MOCK_REVIEWS: Review[] = [
  { user: 'Sophea L.', comment: 'Absolutely love the night cream! My skin feels so soft.', rating: 5, date: '2023-10-15' },
  { user: 'Dara K.', comment: 'The acne set really worked for me after 2 weeks.', rating: 5, date: '2023-10-12' },
  { user: 'Bopha M.', comment: 'Good product, but shipping was a bit slow.', rating: 4, date: '2023-10-08' },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: '#CYRA-8821',
    items: [
      { ...INITIAL_PRODUCTS[0], quantity: 1 },
      { ...INITIAL_PRODUCTS[2], quantity: 1 }
    ],
    total: 60.00,
    status: 'Shipped',
    customer: { name: 'Sokha Dara', phone: '012 999 888', address: '#12, St 200', province: 'Phnom Penh' },
    date: '2023-10-25'
  },
  {
    id: '#CYRA-8835',
    items: [
      { ...INITIAL_PRODUCTS[4], quantity: 2 }
    ],
    total: 24.00,
    status: 'Processing',
    customer: { name: 'Sokha Dara', phone: '012 999 888', address: '#12, St 200', province: 'Phnom Penh' },
    date: '2023-11-02'
  },
  {
    id: '#CYRA-8901',
    items: [
      { ...INITIAL_PRODUCTS[1], quantity: 1 },
      { ...INITIAL_PRODUCTS[3], quantity: 1 },
      { ...INITIAL_PRODUCTS[0], quantity: 1 }
    ],
    total: 88.00,
    status: 'Pending',
    customer: { name: 'Sokha Dara', phone: '012 999 888', address: '#12, St 200', province: 'Phnom Penh' },
    date: '2023-11-05'
  }
];